CREATE DATABASE BD_FAMITEC;
USE BD_FAMITEC;

CREATE TABLE TBL_USUARIO (
ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
USERNAME VARCHAR(200) NOT NULL,
PASS VARCHAR(100) NOT NULL,
ESTADO BIT NOT NULL, 
NIVEL INT NOT NULL
);

CREATE TABLE TBL_PERSONAL (
ID_PERSONAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
NOM_PERSONAL VARCHAR(200) NOT NULL,
DNI_PERSONAL VARCHAR(8) NOT NULL,
EMAIL_PERSONAL VARCHAR(200) NOT NULL
);

CREATE TABLE TBL_ESTADO_DOC (
ID_ESTADO INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
NOM_ESTADO VARCHAR(200) NOT NULL,
DES_ESTADO VARCHAR(200) NOT NULL
);

CREATE TABLE TBL_CONTROL(
ID_CONTROL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PERSONAL INT NOT NULL,
FECHA_DOC DATE NOT NULL, 
FECHA_INICIO_MANTE DATETIME NOT NULL,
FECHA_FIN_MANTE DATETIME NOT NULL,
ID_ESTADO INT NOT NULL,
COSTO_TOTAL DECIMAL NOT NULL,
FOREIGN KEY(ID_PERSONAL) REFERENCES TBL_PERSONAL(ID_PERSONAL),
FOREIGN KEY(ID_ESTADO) REFERENCES TBL_ESTADO_DOC(ID_ESTADO)
);

CREATE TABLE TBL_MATERIALES (
ID_MATERIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
DES_MATERIAL VARCHAR(200) NOT NULL,
COSTO_MATERIAL DECIMAL(7,2) NOT NULL,
UNI_MEDIDA VARCHAR(10) NOT NULL
);

CREATE TABLE TBL_DETALLE_MATERIAL (
ID_MATERIAL INT NOT NULL,
ID_CONTROL INT NOT NULL,
CANT_MATERIAL DECIMAL(7,2) NOT NULL,
COSTO_X_MATERIAL DECIMAL(7,2) NOT NULL,
FOREIGN KEY(ID_MATERIAL) REFERENCES TBL_MATERIALES(ID_MATERIAL),
FOREIGN KEY(ID_CONTROL) REFERENCES TBL_CONTROL(ID_CONTROL),
PRIMARY KEY(ID_MATERIAL,ID_CONTROL)
);

CREATE TABLE TBL_ESTADO_MAQ (
ID_ESTADO_MAQ INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
NOM_ESTADO_MAQ VARCHAR(200) NOT NULL,
DES_ESTADO_MAQ VARCHAR(200) NOT NULL
);

CREATE TABLE TBL_MAQUINARIA(
ID_MAQUINARIA INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
ID_ESTADO_MAQ INT NOT NULL,
NOM_MAQUINARIA VARCHAR(200) NOT NULL,
PROVEEDOR_MAQUINARIA VARCHAR(200) NOT NULL,
DES_MAQUINARIA VARCHAR(255) NOT NULL,
PIEZAS_MAQUINARIAS VARCHAR(255) NOT NULL,
COSTO_HORA_SOLES DECIMAL(7,2) NOT NULL,
COSTO_HORA_DOLARES DECIMAL(7,2) NOT NULL,
ESTADO_MAQUINARIA INT NOT NULL,
FOREIGN KEY(ID_ESTADO_MAQ) REFERENCES TBL_ESTADO_MAQ(ID_ESTADO_MAQ)
);

CREATE TABLE TBL_DETALLE_MAQUINARIA(
ID_CONTROL INT NOT NULL,
ID_MAQUINARIA INT NOT NULL,
CANT_MAQUINARIAS INT NOT NULL,
FOREIGN KEY(ID_CONTROL) REFERENCES TBL_CONTROL(ID_CONTROL),
FOREIGN KEY(ID_MAQUINARIA) REFERENCES TBL_MAQUINARIA(ID_MAQUINARIA),
PRIMARY KEY(ID_CONTROL,ID_MAQUINARIA)
);
